#!/usr/bin/env python3
"""Validate commit messages against repo conventions.

Called from CI with a range of commits to check:
  check-commits.py <range>

The range is a `git rev-list`-compatible argument such as:
  HEAD~n..HEAD    — last n commits
  main..HEAD      — commits ahead of main
"""

import re
import subprocess
import sys

# Allowed types
TYPES = {"feat", "fix", "refactor", "test", "docs", "chore", "perf", "ci"}

# Pattern: type(scope): subject  or  type: subject
COMMIT_PATTERN = re.compile(
    r"^(?P<type>[a-z]+)"        # type
    r"(?:\((?P<scope>[^)]+)\))?"  # optional (scope)
    r":\s(?P<subject>.+)$"      # ': subject'
)


def get_commits(range_arg: str) -> list[str]:
    result = subprocess.run(
        ["git", "rev-list", "--reverse", range_arg],
        capture_output=True, text=True, check=False,
    )
    if result.returncode != 0 or not result.stdout.strip():
        # Fallback: try as a single revision range
        result = subprocess.run(
            ["git", "log", "--format=%H", range_arg],
            capture_output=True, text=True, check=False,
        )
    if not result.stdout.strip():
        # Last resort: just check HEAD (single root commit)
        result = subprocess.run(
            ["git", "log", "--format=%H", "-1", "HEAD"],
            capture_output=True, text=True, check=False,
        )
    return result.stdout.strip().splitlines() if result.stdout.strip() else []


def get_message(sha: str) -> str:
    result = subprocess.run(
        ["git", "log", "--format=%B", "-1", sha],
        capture_output=True, text=True, check=True,
    )
    return result.stdout


def check_commit(sha: str) -> list[str]:
    msg = get_message(sha)
    lines = msg.splitlines()
    errors = []

    if not lines:
        errors.append("empty commit message")
        return errors

    # Skip merge commits — they are generated by GitHub and do not
    # follow conventional commit format.
    if lines[0].startswith("Merge "):
        return errors

    # --- subject line ---
    subject = lines[0]

    # Length
    if len(subject) > 72:
        errors.append(f"subject {len(subject)} chars (max 72): {subject}")

    # Format
    m = COMMIT_PATTERN.match(subject)
    if not m:
        errors.append(f"subject does not match 'type(scope): subject': {subject}")
    else:
        if m.group("type") not in TYPES:
            errors.append(f"unknown type '{m.group('type')}' "
                          f"(allowed: {', '.join(sorted(TYPES))})")
        scope = m.group("scope")
        if scope and not re.match(r"^[a-z][a-z0-9_-]*$", scope):
            errors.append(f"scope should be lowercase alphanumeric: '{scope}'")

    # No trailing period
    if subject.endswith("."):
        errors.append(f"subject ends with period: {subject}")

    # --- body ---
    body_start = 2 if len(lines) > 1 and lines[1] == "" else 1
    body_lines = lines[body_start:]

    # Separate trailers (Signed-off-by lines)
    body_only = [line for line in body_lines if not line.startswith("Signed-off-by:")]

    # Body must not be empty
    body_text = [line for line in body_only if line.strip()]
    if not body_text:
        errors.append("body is empty — explain why the change is needed")

    # Body line length
    for i, line in enumerate(body_only):
        if len(line) > 70:
            errors.append(f"body line {body_start + i + 1} "
                          f"{len(line)} chars (max 70): {line[:70]}...")

    # --- trailers ---
    has_signed_off = any(
        line.startswith("Signed-off-by:") for line in body_lines
    )
    if not has_signed_off:
        errors.append("missing 'Signed-off-by: ...' trailer")

    return errors


def main() -> int:
    range_arg = sys.argv[1] if len(sys.argv) > 1 else "HEAD~1..HEAD"

    shas = get_commits(range_arg)
    if not shas:
        print(f"No commits found in range: {range_arg}")
        return 0

    all_errors: dict[str, list[str]] = {}
    for sha in shas:
        short = sha[:7]
        subject = get_message(sha).splitlines()[0] if get_message(sha) else "(empty)"
        errs = check_commit(sha)
        if errs:
            all_errors[sha] = errs
            print(f"\n--- {short} {subject}")
            for e in errs:
                print(f"  FAIL: {e}")

    if all_errors:
        print(f"\n{len(all_errors)} commit(s) with errors")
        return 1

    print("All commits valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
